package com.vechain.grid.db.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.vechain.grid.db.model.SessionEntity;
import com.vechain.grid.db.model.SessionEntityExample;

public interface SessionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int countByExample(SessionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int deleteByExample(SessionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int insert(SessionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int insertSelective(SessionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    List<SessionEntity> selectByExample(SessionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    SessionEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") SessionEntity record, @Param("example") SessionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int updateByExample(@Param("record") SessionEntity record, @Param("example") SessionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int updateByPrimaryKeySelective(SessionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorized_session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    int updateByPrimaryKey(SessionEntity record);
}