package com.vechain.grid.db.model;

import java.util.Date;

public class SessionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.id
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.request_no
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private String requestNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private String session;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.auth_url
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private String authUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.status
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.extra_params
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private String extraParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.time_out
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private Integer timeOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.type
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.update_time
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.create_time
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorized_session.expire
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    private Integer expire;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.id
     *
     * @return the value of authorized_session.id
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.id
     *
     * @param id the value for authorized_session.id
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.request_no
     *
     * @return the value of authorized_session.request_no
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public String getRequestNo() {
        return requestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.request_no
     *
     * @param requestNo the value for authorized_session.request_no
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.session
     *
     * @return the value of authorized_session.session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public String getSession() {
        return session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.session
     *
     * @param session the value for authorized_session.session
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setSession(String session) {
        this.session = session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.auth_url
     *
     * @return the value of authorized_session.auth_url
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public String getAuthUrl() {
        return authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.auth_url
     *
     * @param authUrl the value for authorized_session.auth_url
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setAuthUrl(String authUrl) {
        this.authUrl = authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.status
     *
     * @return the value of authorized_session.status
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.status
     *
     * @param status the value for authorized_session.status
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.extra_params
     *
     * @return the value of authorized_session.extra_params
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public String getExtraParams() {
        return extraParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.extra_params
     *
     * @param extraParams the value for authorized_session.extra_params
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setExtraParams(String extraParams) {
        this.extraParams = extraParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.time_out
     *
     * @return the value of authorized_session.time_out
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public Integer getTimeOut() {
        return timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.time_out
     *
     * @param timeOut the value for authorized_session.time_out
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setTimeOut(Integer timeOut) {
        this.timeOut = timeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.type
     *
     * @return the value of authorized_session.type
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.type
     *
     * @param type the value for authorized_session.type
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.update_time
     *
     * @return the value of authorized_session.update_time
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.update_time
     *
     * @param updateTime the value for authorized_session.update_time
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.create_time
     *
     * @return the value of authorized_session.create_time
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.create_time
     *
     * @param createTime the value for authorized_session.create_time
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorized_session.expire
     *
     * @return the value of authorized_session.expire
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public Integer getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authorized_session.expire
     *
     * @param expire the value for authorized_session.expire
     *
     * @mbggenerated Thu Aug 15 15:05:34 CST 2019
     */
    public void setExpire(Integer expire) {
        this.expire = expire;
    }
}